Ecommerce/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from decouple import config
from rest_framework import routers
from rest_framework.authtoken import views
from main.api.views import (
    ItemViewSet,
    MyOrderViewSet,
    CurrentCartViewSet,
    AddressViewSet,
    registration,
    get_paytm_creditionals,
)

router = routers.DefaultRouter()
router.register("items", ItemViewSet, basename="items")
router.register("myOrder", MyOrderViewSet, basename="myOrder")
router.register("cart", CurrentCartViewSet, basename="cart")
router.register("address", AddressViewSet, basename="address")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
    path("accounts/", include("allauth.urls")),
    path("", include("main.urls", namespace="main")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-token-auth/", views.obtain_auth_token),
    path("signUp/", registration, name="signUp"),
    path("get_paytm_creditionals/", get_paytm_creditionals, name="paytm-creditionals"),
]

if config("DEBUG"):
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path,include
from .views import (
    HomeView,
    ProductDetail,
    add_to_cart,
    remove_from_cart,
    OrderSummary,
    remove_single_item_from_cart,
    CheckOut,
    PaymentView,
    add_coupon,
    RefundView,
    PaytmCallback,
    OrderListView,
    OrderStatus,
    )

app_name = 'main'



urlpatterns = [
    
    path('', HomeView.as_view(), name='home'),
    path('myorder/',OrderListView.as_view(), name='myorderlist'),
    path('product/<slug>', ProductDetail.as_view(),name='product-detail'),
    path('add_to_cart/<slug>',add_to_cart,name='add-to-cart'),
    path('remove_from_cart/<slug>',remove_from_cart,name='remove-from-cart'),
    path('remove_single_item_from_cart/<slug>',remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('order_summary/', OrderSummary.as_view(),name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(),name='payment'),
    path('checkout/', CheckOut.as_view(),name='checkout'),
    path('add_coupon/', add_coupon ,name='add-coupon'),
    path('refund/', RefundView.as_view() ,name='refund'),
    path('payment_confirmation/', PaytmCallback ,name='paytm-confirmation'),
    path('order_status/<str:ref_code>',OrderStatus.as_view(),name='orderStatus'),
    

]

main/models.py
from django.db import models
from django.urls import reverse
from django.conf.global_settings import AUTH_USER_MODEL as User
from django.utils.text import slugify
from django_countries.fields import CountryField
import channels.layers
from django.dispatch import receiver
from asgiref.sync import async_to_sync
import json
from django.db.models.signals import post_save, pre_save
import random, string
from rest_framework.authtoken.models import Token


def create_ref(k):
    return "".join(
        random.choices(string.ascii_lowercase + string.ascii_uppercase, k=10)
    )


Category_choices = (("S", "Shirt"), ("SW", "Sportwear"), ("OW", "Outwear"))

Label_choices = (("P", "primary"), ("S", "secondary"), ("D", "danger"))

order_status_choices = (
    ("ORD", "Order Received"),
    ("OFD", "Out For Delivery"),
    ("D", "Dispatch"),
    ("OD", "Order Delivered"),
)
# Create your models here.
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zipcode = models.CharField(max_length=10)
    use_default_shipping = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class PaymentViaPaytm(models.Model):
    order_id = models.CharField(max_length=250)
    checksum = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(default=0)
    category = models.CharField(choices=Category_choices, max_length=2)
    label = models.CharField(choices=Label_choices, max_length=1)
    description = models.TextField(default="", blank=True)
    slug = models.SlugField()
    image = models.ImageField(upload_to="item/images", blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_item_price(self):
        return self.price - self.discount_price

    def get_absolute_url(self):
        return reverse("main:product-detail", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_total_amount(self):
        return self.quantity * self.item.price - self.get_discount_amount()

    def get_discount_amount(self):
        if self.item.discount_price:
            return self.quantity * self.item.discount_price
        return 0

    def get_amount_saved(self):
        if self.item.discount_price:
            return self.get_total_amount() - self.get_discount_amount()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateField(null=True)
    shipping_address = models.ForeignKey(
        "Address",
        related_name="shipping_address",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    payment = models.ForeignKey(
        Payment,
        related_name="Payment",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    payment_via_paytm = models.ForeignKey(
        "PaymentViaPaytm", on_delete=models.SET_NULL, blank=True, null=True
    )
    coupon = models.ManyToManyField("Coupon", blank=True)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    order_status = models.CharField(
        choices=order_status_choices, max_length=4, default="ORD"
    )
    ref_code = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("main:orderStatus", kwargs={"ref_code": self.ref_code})

    def save(self, *args, **kwargs):
        if self.ref_code == None:
            self.ref_code = create_ref(10)
        super(Order, self).save(*args, **kwargs)

    def get_final_amount(self):
        total = 0
        for x in self.items.all():
            total += x.get_total_amount()
        if self.coupon.all():
            for coupon in self.coupon.all():
                total -= coupon.amount
        return total


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.CharField(max_length=200)
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


@receiver(post_save, sender=Order)
def order_status_handler(sender, instance, created, **kwargs):
    if not created:
        channels_layer = channels.layers.get_channel_layer()
        data = {}
        data["order_id"] = instance.id
        data["amount"] = instance.get_final_amount()
        data["status"] = instance.get_order_status_display()
        data["date"] = str(instance.ordered_date)
        progress_percentage = 20
        if instance.order_status == "Order Recieved":
            progress_percentage = 20
        elif instance.order_status == "Dispatch":
            progress_percentage = 50
        elif instance.order_status == "Out For Delivery":
            progress_percentage = 80
        elif instance.order_status == "Order Delivered":
            progress_percentage = 100
        data["progress"] = progress_percentage

        async_to_sync(channels_layer.group_send)(
            "order_%s" % instance.id,
            {"type": "order_status", "payload": json.dumps(data)},
        )


class PaytmParams:
    def __init__(
        self,
        MID,
        ORDER_ID,
        CUST_ID,
        TXN_AMOUNT,
        CHANNEL_ID,
        WEBSITE,
        INDUSTRY_TYPE_ID,
        CALLBACK_URL,
        CHECKSUMHASH,
    ):
        self.MID = MID
        self.ORDER_ID = ORDER_ID
        self.CUST_ID = CUST_ID
        self.TXN_AMOUNT = TXN_AMOUNT
        self.CHANNEL_ID = CHANNEL_ID
        self.WEBSITE = WEBSITE
        self.INDUSTRY_TYPE_ID = INDUSTRY_TYPE_ID
        self.CALLBACK_URL = CALLBACK_URL
        self.CHECKSUMHASH = CHECKSUMHASH


@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    .card {

      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);

    }

    .card:hover {
      transform: scale(1.02) translateY(-1px);
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>

  {% include 'navbar.html' %}
  <!-- messages -->
  <div class="mt-5 pt-4">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}

  {% block extra_body %}
  {% endblock %}

  {% include 'footer.html' %}

  <!-- SCRIPTS -->
  <!-- JQuery -->


  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">


  </script>
  {% block extra_scripts %}
  {% endblock %}
</body>

</html>

templates/callback_response.html
{% extends 'base.html' %}


{% block head_title %}
    Payment Detail
{% endblock  %}


{% block content %}
<h2>Callback Messsage: </h2>                    <br>
<h3> Checksum Verification: {{ message }} </h3> <br>
MID: {{ MID }}                                  <br>
TXNID: {{ TXNID }}                              <br>
ORDERID: {{ ORDERID }}                          <br>
BANKTXNID: {{ BANKTXNID }}                      <br>
TXNAMOUNT: {{ TXNAMOUNT }}                      <br>
CURRENCY: {{ CURRENCY }}                        <br>
<h3> STATUS: {{ STATUS }} </h3>                 <br>
RESPCODE: {{ RESPCODE }}                        <br>
RESPMSG: {{ RESPMSG }}                          <br>
TXNDATE: {{ TXNDATE }}                          <br>
GATEWAYNAME: {{ GATEWAYNAME }}                  <br>
BANKNAME: {{ BANKNAME }}                        <br>
BIN_NAME: {{ BIN_NAME }}                        <br>
PAYMENTMODE: {{ PAYMENTMODE }}                  <br>
CHECKSUMHASH: {{ CHECKSUMHASH }}
{% endblock  %}
    
    

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4  fadeIn" >

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/home-page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %} Home{% endblock %}
{% block content %}


<!--Main layout-->
<main>
  <div class="container">

    <hr>

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">


            <div class="view overlay">
              <a href="{% url 'main:product-detail' item.slug %}">
                {% if item.image %}
                <img src="{{ item.image.url }}" class="card-img-top">
                {% endif %}
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.name }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">
                      {% if item.get_label_display == 'primary' %}
                      Bestseller
                      {% else %}
                      NEW
                      {% endif %}
                    </span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong> Rs.

                  {{ item.get_item_price }}

                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}



      </div>
      <!--Grid row-->



    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        {% if is_paginated %}

        {% if page_obj.has_previous%}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}"> {{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
      {% endif %}
    </nav>
    <!--Pagination-->

  </div>
</main>
<!--Main layout-->
{% endblock %}

templates/myorderlist-page.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    {% if object_list.empty %}
    <h1>You have not placed an order yet !!!</h1>

    {% else %}

    <ul class="list-group">
        {% for order in object_list %}
        <li class="list-group-item"> <a href="{{ order.get_absolute_url }}">Order ref code : {{order.ref_code}}</a></li>

        {% endfor %}
    </ul>





    {% endif %}
</div>

{% endblock %}

templates/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'main:home' %}">
      <strong class="blue-text">E-commerce</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">


      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}

        <li class="nav-item">
          <a href="{% url 'main:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}

      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

templates/order-status.html
{% extends 'base.html' %}


{% block content %}
    <div>
        
        <h2>Order Status: <p id="status">{{object.order_status}} </p></h2>
        
        <div class="progress">
            <div class="progress-bar progress-bar-striped " role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>

    </div>
{% endblock  %}

{% block extra_scripts %}
<script>
    var order_id = '{{object.id}}'
    let socket = new WebSocket('ws://' + window.location.host + '/ws/status/' + order_id + '/');
    socket.onopen = function (e) {
      console.log('Connection established');
    };
  
    socket.onmessage = function (e) {
      var data = JSON.parse(e.data)
      var value = data.payload.progress
      var status = data.payload.status
      console.log(data)
      
      increaseProgress(value )
      changestatus(status)
  
    };
    socket.onclose = function (e) {
      console.log('Connection closed');
    };

    function changestatus(status){
      var orderStatus = document.getElementById('status')
      orderStatus.innerHTML = status
    }
  
    function increaseProgress(value ){
      var progress = document.querySelector('.progress-bar')
      if(value == 100){
        console.log("ss")
        progress.classList.add('bg-success')
      }
      progress.style.width = value + "%"
    }
  
    
  
  </script>
{% endblock %}
    

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul id="lroup" class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.name }}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">${{ order_item.get_total_amount }}</span>
        </li>
        {% endfor %}
        <div id="promocodehide" style="display:none;">
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small id="appliedcoupon"></small>
                </div>
                <span class="text-success">-</span>
            </li>
        </div>



        {% if order.coupon.count != 0 %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-{{ order.coupon.amount }}</span>
        </li>
        {% endif %}



        <li class="list-group-item d-flex justify-content-between">
            <span>Total </span>
            <strong id="totalamount">{{ order.get_final_amount }}</strong>
        </li>
    </ul>


    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2 " action="{% url 'main:add-coupon' %}" method="POST" id="cpost-form">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">

                <button class="btn btn-secondary btn-sm mt-2 ml-2 waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}




</div>

templates/order_summary.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}Order Summary{% endblock %}
{% block content %}


<!--Main layout-->
<main>
  <div class="container">


    {% if object.items.count == 0 %}
    <H1>You don't have any item in the cart.</H1>
    {% else %}
    <!--Table-->
    <table class="table table-striped w-auto mt-5 mb-5">

      <!--Table head-->
      <thead>
        <tr>
          <th class="th-lg">#</th>
          <td class="th-lg">Item</td>
          <td class="th-lg">Price</td>
          <td class="th-lg">Quantity</td>
          <td class="th-lg">Total price</td>
        </tr>
      </thead>
      <!--Table head-->

      <!--Table body-->
      <tbody>

        {% for order in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ order.item.name }}</td>
          <td>{{ order.item.price }}</td>
          <td>
            <a href="{% url 'main:remove-single-item-from-cart' order.item.slug %}"><i
                class="fas fa-minus mr-2"></i></a>
            {{ order.quantity }}
            <a href="{% url 'main:add-to-cart' order.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
          </td>
          <td>{{ order.get_total_amount }}</td>
          <td><a class="btn btn-danger btn-sm" href="{% url 'main:remove-from-cart' order.item.slug %}">Remove</a>
          </td>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="4"><b> Final Amount : </b></td>
          <td><b> {{ object.get_final_amount }}</b></td>
        </tr>
        <tr>
          <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
          </td>
        </tr>

      </tbody>
      <!--Table body-->


    </table>
    <!--Table-->
    {% endif %}








  </div>
</main>
<!--Main layout-->
{% endblock %}

templates/product-page.html
{% extends 'base.html' %}
{% block head_title %}Product Detail{% endblock %}
{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">
        {% if object.image %}
        <img src="{{ object.image.url }}" class="img-fluid" alt="Not Found">
        {% endif %}
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-1">

          <div class="mb-3">
            <h1>{{ object.name }}</h1>
            <a href="">
              <span class="badge purple mr-1">{{ object.get_category_display }}</span>
            </a>
            <a href="">
              <span class="badge badge-pill {{ object.get_label_display }}-color">
                {% if object.get_label_display == 'primary' %}
                Bestseller
                {% else %}
                NEW
                {% endif %}
              </span>
            </a>
          </div>

          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
              <del>{{ object.price }}</del>
            </span>
            <span>{{ object.get_item_price }}</span>
            {% else %}
            <span>{{ object.price }}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque tempore reprehenderit maiores eaque minus, molestias ipsum architecto deleniti ut animi illo atque qui labore non beatae iste explicabo nesciunt quasi.</p>

          <a class="btn btn-primary btn-md my-0 p" href="{% url 'main:add-to-cart' slug=object.slug %}" type="submit">Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->

{% endblock %}